title: "Gabriel Olivier"
author: "Gabriel Olivier"
description: "Tulane University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About Me", sidebaricon: home}
  - {file: "CV.pdf", title: "CV", sidebaricon: home}
  - {file: "research.md", title: "Research", sidebaricon: home}
  - {file: "teaching.md", title: "Teaching", sidebaricon: home}


external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:golivier1@tulane.edu"}
  - {title: LinkedIn, icon: linkdin, url: "https://www.linkedin.com/in/gabriel-olivier-1740b2242/"}
 

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
